name: Update Homebrew Cask

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew Cask version
        # 注意下面這行：雖然名字叫 formula，但它裡面有支援更新 cask 的參數
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_PAT }}
          tap: Liaoyork/homebrew-tap
          cask: appswitcher # 這裡指定 cask，它就會去你的 Casks 資料夾找 appswitcher.rb
